In [1]:
# Assignment 1: Building Multi-Layer Perceptrons (MLPs) and Convolutional Neural Networks (CNNs) with PyTorch
import os
import torch
from torch import nn
from torch.utils.data import DataLoader, random_split
from torchvision import datasets, transforms
from torchvision.transforms import v2
import torch.nn.functional as F
import torch.optim as optim


torch.manual_seed(42)
# Change runtimetype to t4GPU
# Set device to "mps" if macbook else "cuda"
#device = "mps" if torch.backends.mps.is_available() else "cpu"
device = "cuda" if torch.cuda.is_available() else "cpu"

In [2]:
## Task 1: Learn the basics of PyTorch
### Data Loading
transform = v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])

# Download training data from open datasets.
training_fashion = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=transform,
)

# Download test data from open datasets.
test_fashion = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=transform,
)

# Split 10% of the training data for validation
generator = torch.Generator().manual_seed(42)
train_fashion, val_fashion = random_split(training_fashion, [54000, 6000], generator=generator)

In [3]:
batch_size = 64
# Create data loaders.
train_dataloader = DataLoader(train_fashion, batch_size=batch_size, shuffle=True)
test_dataloader = DataLoader(test_fashion, batch_size=batch_size)
val_dataloader = DataLoader(val_fashion, batch_size=batch_size)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64

In [4]:
# Sanity check made by AI to see if everything worked as it is supossed to (can be removed)
print("device:", device)
print("sizes:", len(train_fashion), len(val_fashion), len(test_fashion))

for name, loader in [("train", train_dataloader), ("val", val_dataloader), ("test", test_dataloader)]:
    X, y = next(iter(loader))
    print(f"{name}: X {tuple(X.shape)} {X.dtype}, range [{X.min():.2f}, {X.max():.2f}] | y {tuple(y.shape)}, labels {y.unique().tolist()}")

device: cuda
sizes: 54000 6000 10000
train: X (64, 1, 28, 28) torch.float32, range [0.00, 1.00] | y (64,), labels [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
val: X (64, 1, 28, 28) torch.float32, range [0.00, 1.00] | y (64,), labels [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
test: X (64, 1, 28, 28) torch.float32, range [0.00, 1.00] | y (64,), labels [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
### Making the baseline Multi-Layer Perceptron (MLP)
#### Defining the MLP
class MLP(nn.Module):
    def __init__(self, activation=nn.ReLU, width=512, dropout=0, depth=2, init=None, in_features= 28 * 28):
        super().__init__()
        self.flatten = nn.Flatten()

        layers = []
        for _ in range(depth):
            layers += [
                nn.Linear(in_features, width),
                activation(),
                nn.Dropout(dropout),
            ]
            in_features = width
        layers.append(nn.Linear(in_features, 10))

        self.layers = nn.Sequential(*layers)

        # Initialization
        if init is not None:
            for m in self.modules():
                if isinstance(m, nn.Linear):
                    init(m.weight)
                    nn.init.zeros_(m.bias)

    def forward(self, x):
        x = self.flatten(x)
        return self.layers(x)

In [6]:
def train_epoch(model, dataloader, loss_fn, optimizer):
    model.train()
    total_loss = 0
    size = len(dataloader.dataset)
    num_batches = len(dataloader)


    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        total_loss += loss.item()

        # Updates during process by giving loss every 100th batch
        if batch % 100 == 0:
            loss, current = loss.item(), batch * batch_size + len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

    return total_loss / num_batches

def evaluate(model, dataloader, loss_fn):
    model.eval()
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    avg_loss = test_loss / num_batches
    accuracy  = correct / size

    return avg_loss, accuracy

In [7]:
#### Defining the parameters and let the run model learn
learning_rate = 1e-3
batch_size = 64
epochs = 15

torch.manual_seed(42)
model = MLP().to(device)
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

history = {"train_loss": [], "val_loss": [], "val_acc": []}
for epoch in range(epochs):
    train_loss = train_epoch(model, train_dataloader, loss_fn, optimizer)
    val_loss, val_acc = evaluate(model, val_dataloader, loss_fn)
    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)
    history["val_acc"].append(val_acc)
    print(f"epoch {epoch+1}: train loss {train_loss:.4f} | val loss {val_loss:.4f} | val acc {val_acc:.4f}")

loss: 2.304710  [   64/54000]
loss: 0.581906  [ 6464/54000]
loss: 0.740273  [12864/54000]
loss: 0.549249  [19264/54000]
loss: 0.429783  [25664/54000]
loss: 0.399725  [32064/54000]
loss: 0.302493  [38464/54000]
loss: 0.269962  [44864/54000]
loss: 0.400666  [51264/54000]
epoch 1: train loss 0.4977 | val loss 0.3970 | val acc 0.8545
loss: 0.382782  [   64/54000]
loss: 0.500927  [ 6464/54000]
loss: 0.299008  [12864/54000]
loss: 0.378017  [19264/54000]
loss: 0.517513  [25664/54000]
loss: 0.309144  [32064/54000]
loss: 0.405992  [38464/54000]
loss: 0.441055  [44864/54000]
loss: 0.452673  [51264/54000]
epoch 2: train loss 0.3644 | val loss 0.3594 | val acc 0.8692
loss: 0.498490  [   64/54000]
loss: 0.273027  [ 6464/54000]
loss: 0.335654  [12864/54000]
loss: 0.241411  [19264/54000]
loss: 0.414015  [25664/54000]
loss: 0.348818  [32064/54000]
loss: 0.198713  [38464/54000]
loss: 0.332987  [44864/54000]
loss: 0.287863  [51264/54000]
epoch 3: train loss 0.3242 | val loss 0.3688 | val acc 0.8673
loss: 0.367223  [   64/54000]
loss: 0.286319  [ 6464/54000]
loss: 0.211007  [12864/54000]
loss: 0.480594  [19264/54000]
loss: 0.307226  [25664/54000]
loss: 0.349680  [32064/54000]
loss: 0.245469  [38464/54000]
loss: 0.334458  [44864/54000]
loss: 0.246861  [51264/54000]
epoch 4: train loss 0.3019 | val loss 0.3604 | val acc 0.8667
loss: 0.246430  [   64/54000]
loss: 0.283582  [ 6464/54000]
loss: 0.388502  [12864/54000]
loss: 0.404881  [19264/54000]
loss: 0.330931  [25664/54000]
loss: 0.201887  [32064/54000]
loss: 0.190753  [38464/54000]
loss: 0.386293  [44864/54000]
loss: 0.362081  [51264/54000]
epoch 5: train loss 0.2809 | val loss 0.3181 | val acc 0.8833
loss: 0.296613  [   64/54000]
loss: 0.153450  [ 6464/54000]
loss: 0.241279  [12864/54000]
loss: 0.361519  [19264/54000]
loss: 0.222807  [25664/54000]
loss: 0.354930  [32064/54000]
loss: 0.341695  [38464/54000]
loss: 0.298216  [44864/54000]
loss: 0.215926  [51264/54000]
epoch 6: train loss 0.2676 | val loss 0.3374 | val acc 0.8795
loss: 0.200781  [   64/54000]
loss: 0.149467  [ 6464/54000]
loss: 0.374981  [12864/54000]
loss: 0.264246  [19264/54000]
loss: 0.383640  [25664/54000]
loss: 0.200763  [32064/54000]
loss: 0.198049  [38464/54000]
loss: 0.272790  [44864/54000]
loss: 0.145198  [51264/54000]
epoch 7: train loss 0.2533 | val loss 0.3108 | val acc 0.8842
loss: 0.152186  [   64/54000]
loss: 0.167590  [ 6464/54000]
loss: 0.200025  [12864/54000]
loss: 0.179035  [19264/54000]
loss: 0.357099  [25664/54000]
loss: 0.270507  [32064/54000]
loss: 0.263195  [38464/54000]
loss: 0.254719  [44864/54000]
loss: 0.338081  [51264/54000]
epoch 8: train loss 0.2376 | val loss 0.3364 | val acc 0.8800
loss: 0.333120  [   64/54000]
loss: 0.189115  [ 6464/54000]
loss: 0.300401  [12864/54000]
loss: 0.197209  [19264/54000]
loss: 0.302681  [25664/54000]
loss: 0.199279  [32064/54000]
loss: 0.285660  [38464/54000]
loss: 0.189742  [44864/54000]
loss: 0.251937  [51264/54000]
epoch 9: train loss 0.2296 | val loss 0.3201 | val acc 0.8857
loss: 0.195626  [   64/54000]
loss: 0.179047  [ 6464/54000]
loss: 0.161952  [12864/54000]
loss: 0.182211  [19264/54000]
loss: 0.152846  [25664/54000]
loss: 0.204809  [32064/54000]
loss: 0.236126  [38464/54000]
loss: 0.246061  [44864/54000]
loss: 0.180261  [51264/54000]
epoch 10: train loss 0.2171 | val loss 0.3360 | val acc 0.8862
loss: 0.135267  [   64/54000]
loss: 0.203947  [ 6464/54000]
loss: 0.130194  [12864/54000]
loss: 0.099111  [19264/54000]
loss: 0.167987  [25664/54000]
loss: 0.133894  [32064/54000]
loss: 0.222647  [38464/54000]
loss: 0.088959  [44864/54000]
loss: 0.063481  [51264/54000]
epoch 11: train loss 0.2056 | val loss 0.3349 | val acc 0.8855
loss: 0.255270  [   64/54000]
loss: 0.194125  [ 6464/54000]
loss: 0.202199  [12864/54000]
loss: 0.215334  [19264/54000]
loss: 0.223185  [25664/54000]
loss: 0.170288  [32064/54000]
loss: 0.171111  [38464/54000]
loss: 0.155805  [44864/54000]
loss: 0.140240  [51264/54000]
epoch 12: train loss 0.2013 | val loss 0.3262 | val acc 0.8908
loss: 0.076227  [   64/54000]
loss: 0.129323  [ 6464/54000]
loss: 0.282804  [12864/54000]
loss: 0.168440  [19264/54000]
loss: 0.197412  [25664/54000]
loss: 0.238551  [32064/54000]
loss: 0.121359  [38464/54000]
loss: 0.275216  [44864/54000]
loss: 0.282404  [51264/54000]
epoch 13: train loss 0.1915 | val loss 0.3319 | val acc 0.8915
loss: 0.216123  [   64/54000]
loss: 0.090370  [ 6464/54000]
loss: 0.138498  [12864/54000]
loss: 0.222952  [19264/54000]
loss: 0.139094  [25664/54000]
loss: 0.201907  [32064/54000]
loss: 0.369628  [38464/54000]
loss: 0.298466  [44864/54000]
loss: 0.196259  [51264/54000]
epoch 14: train loss 0.1831 | val loss 0.3445 | val acc 0.8930
loss: 0.121978  [   64/54000]
loss: 0.094976  [ 6464/54000]
loss: 0.354791  [12864/54000]
loss: 0.209657  [19264/54000]
loss: 0.139188  [25664/54000]
loss: 0.127909  [32064/54000]
loss: 0.117972  [38464/54000]
loss: 0.194227  [44864/54000]
loss: 0.206597  [51264/54000]
epoch 15: train loss 0.1767 | val loss 0.3659 | val acc 0.8953

In [34]:
def train_for_configuration_and_datasets(cfg, train_dataloader, val_dataloader, results, in_features, name):
    
    print(f'training with config {cfg}')

    best_val_loss = float("inf")
    bad_epochs = 0
    torch.manual_seed(42)
    loss_fn = nn.CrossEntropyLoss()

    model = MLP(activation=activations[cfg["activation"]], 
                width=cfg["width"], 
                dropout=cfg["dropout"], 
                depth=cfg["depth"],
                init=inits[cfg["init"]],
                in_features=in_features
                ).to(device)

    optimizer = optimizers[cfg["optimizer"]](
        model.parameters(), lr=cfg["lr"], weight_decay=cfg["weight_decay"]
    )

    history = {"train_loss": [], "val_loss": [], "val_acc": []}

    for epoch in range(cfg["epochs"]):
        train_loss = train_epoch(model, train_dataloader, loss_fn, optimizer)
        val_loss, val_acc = evaluate(model, val_dataloader, loss_fn)
        

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            bad_epochs = 0
        else:
            bad_epochs += 1
            if bad_epochs >= cfg["patience"]:
                print(f"Early stopping - epoch {epoch}")
                break

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)
        print(f"epoch {epoch+1}: train loss {train_loss:.4f} | val loss {val_loss:.4f} | val acc {val_acc:.4f}")

    best_epoch = history["val_loss"].index(best_val_loss)
    results.append({
        "name": name, **cfg,
        "config":cfg,
        "best_val_loss": best_val_loss,
        "best_val_acc": history["val_acc"][best_epoch],
        "best_epoch": best_epoch + 1,
        "params": sum(p.numel() for p in model.parameters()),
        "history": history,
    })

In [28]:
from functools import partial
import pandas as pd

activations = {
    "relu": nn.ReLU,
    "leaky_relu": partial(nn.LeakyReLU, 0.01),
    "gelu": nn.GELU,
    "tanh": nn.Tanh,
}
inits = {
    "default": None,                                    # PyTorch's built-in init
    "kaiming": nn.init.kaiming_normal_,
    "xavier": nn.init.xavier_uniform_,
    "normal": partial(nn.init.normal_, mean=0.0, std=0.01),
}
optimizers = {
    "sgd": partial(optim.SGD, momentum=0.9),
    "adam": optim.Adam,                                 # weight_decay here = L2 penalty
    "adamw": optim.AdamW,                               # weight_decay here = decoupled decay
}

# ---------------- Configuration ----------------
base = dict(
    init="default", activation="relu",
    optimizer="adam", lr=1e-3,
    dropout=0.0, weight_decay=0.0,
    depth=2, width=512,
    epochs=15, patience=3,
)

# Each entry changes only what differs from the baseline (one factor at a time)
variations = [
    {},                                                 # baseline
    # parameter initialization
    {"init": "kaiming"}, {"init": "xavier"}, {"init": "normal"},
    # activation functions
    {"activation": "leaky_relu"}, {"activation": "gelu"}, {"activation": "tanh"},
    # optimizers + learning rates (paired, since good lr depends on the optimizer)
    {"optimizer": "sgd", "lr": 0.1}, {"optimizer": "sgd", "lr": 0.01},
    {"optimizer": "adam", "lr": 1e-4},
    {"optimizer": "adamw", "lr": 1e-3}, {"optimizer": "adamw", "lr": 1e-4},
    # regularization
    {"dropout": 0.2}, {"dropout": 0.5},
    {"weight_decay": 1e-4},                             # L2 penalty via Adam
    {"optimizer": "adamw", "weight_decay": 1e-2},       # decoupled weight decay
    {"dropout": 0.2, "optimizer": "adamw", "weight_decay": 1e-2},
    # architecture
    {"depth": 1}, {"depth": 4},
    {"width": 128}, {"width": 1024},
]
configs = [base | v for v in variations]
results = []


for i, (cfg, change) in enumerate(zip(configs, variations), 1):
    name = ", ".join(f"{k}={v}" for k, v in change.items()) or "baseline"
    print(f"\n=== {i}/{len(configs)}: {name} ===")

    train_for_configuration_and_datasets(cfg=cfg,
                                         train_dataloader=train_dataloader,
                                         val_dataloader=val_dataloader,
                                         results=results,
                                         in_features=28 * 28,
                                         name=name)

df = pd.DataFrame(results).drop(columns="history").sort_values("best_val_loss")
df

=== 1/21: baseline ===
training cifar with config {'init': 'default', 'activation': 'relu', 'optimizer': 'adam', 'lr': 0.001, 'dropout': 0.0, 'weight_decay': 0.0, 'depth': 2, 'width': 512, 'epochs': 15, 'patience': 3}
loss: 2.304710  [   64/54000]
loss: 0.581906  [ 6464/54000]
loss: 0.740273  [12864/54000]
loss: 0.549249  [19264/54000]
loss: 0.429783  [25664/54000]
loss: 0.399725  [32064/54000]
loss: 0.302493  [38464/54000]
loss: 0.269962  [44864/54000]
loss: 0.400666  [51264/54000]
epoch 1: train loss 0.4977 | val loss 0.3970 | val acc 0.8545
loss: 0.382782  [   64/54000]
loss: 0.500927  [ 6464/54000]
loss: 0.299008  [12864/54000]
loss: 0.378017  [19264/54000]
loss: 0.517513  [25664/54000]
loss: 0.309144  [32064/54000]
loss: 0.405992  [38464/54000]
loss: 0.441055  [44864/54000]
loss: 0.452673  [51264/54000]
epoch 2: train loss 0.3644 | val loss 0.3594 | val acc 0.8692
loss: 0.498490  [   64/54000]
loss: 0.273027  [ 6464/54000]
loss: 0.335654  [12864/54000]
loss: 0.241411  [19264/54000]
loss: 0.414015  [25664/54000]
loss: 0.348818  [32064/54000]
loss: 0.198713  [38464/54000]
loss: 0.332987  [44864/54000]
loss: 0.287863  [51264/54000]
epoch 3: train loss 0.3242 | val loss 0.3688 | val acc 0.8673
loss: 0.367223  [   64/54000]
loss: 0.286319  [ 6464/54000]
loss: 0.211007  [12864/54000]
loss: 0.480594  [19264/54000]
loss: 0.307226  [25664/54000]
loss: 0.349680  [32064/54000]
loss: 0.245469  [38464/54000]
loss: 0.334458  [44864/54000]
loss: 0.246861  [51264/54000]
epoch 4: train loss 0.3019 | val loss 0.3604 | val acc 0.8667
loss: 0.246430  [   64/54000]
loss: 0.283582  [ 6464/54000]
loss: 0.388502  [12864/54000]
loss: 0.404881  [19264/54000]
loss: 0.330931  [25664/54000]
loss: 0.201887  [32064/54000]
loss: 0.190753  [38464/54000]
loss: 0.386293  [44864/54000]
loss: 0.362081  [51264/54000]
epoch 5: train loss 0.2809 | val loss 0.3181 | val acc 0.8833
loss: 0.296613  [   64/54000]
loss: 0.153450  [ 6464/54000]
loss: 0.241279  [12864/54000]
loss: 0.361519  [19264/54000]
loss: 0.222807  [25664/54000]
loss: 0.354930  [32064/54000]
loss: 0.341695  [38464/54000]
loss: 0.298216  [44864/54000]
loss: 0.215926  [51264/54000]
epoch 6: train loss 0.2676 | val loss 0.3374 | val acc 0.8795
loss: 0.200781  [   64/54000]
loss: 0.149467  [ 6464/54000]
loss: 0.374981  [12864/54000]
loss: 0.264246  [19264/54000]
loss: 0.383640  [25664/54000]
loss: 0.200763  [32064/54000]
loss: 0.198049  [38464/54000]
loss: 0.272790  [44864/54000]
loss: 0.145198  [51264/54000]
epoch 7: train loss 0.2533 | val loss 0.3108 | val acc 0.8842
loss: 0.152186  [   64/54000]
loss: 0.167590  [ 6464/54000]
loss: 0.200025  [12864/54000]
loss: 0.179035  [19264/54000]
loss: 0.357099  [25664/54000]
loss: 0.270507  [32064/54000]
loss: 0.263195  [38464/54000]
loss: 0.254719  [44864/54000]
loss: 0.338081  [51264/54000]
epoch 8: train loss 0.2376 | val loss 0.3364 | val acc 0.8800
loss: 0.333120  [   64/54000]
loss: 0.189115  [ 6464/54000]
loss: 0.300401  [12864/54000]
loss: 0.197209  [19264/54000]
loss: 0.302681  [25664/54000]
loss: 0.199279  [32064/54000]
loss: 0.285660  [38464/54000]
loss: 0.189742  [44864/54000]
loss: 0.251937  [51264/54000]
epoch 9: train loss 0.2296 | val loss 0.3201 | val acc 0.8857
loss: 0.195626  [   64/54000]
loss: 0.179047  [ 6464/54000]
loss: 0.161952  [12864/54000]
loss: 0.182211  [19264/54000]
loss: 0.152846  [25664/54000]
loss: 0.204809  [32064/54000]
loss: 0.236126  [38464/54000]
loss: 0.246061  [44864/54000]
loss: 0.180261  [51264/54000]
Early stopping - epoch 9

=== 2/21: init=kaiming ===
training cifar with config {'init': 'kaiming', 'activation': 'relu', 'optimizer': 'adam', 'lr': 0.001, 'dropout': 0.0, 'weight_decay': 0.0, 'depth': 2, 'width': 512, 'epochs': 15, 'patience': 3}
loss: 2.509323  [   64/54000]
loss: 0.478309  [ 6464/54000]
loss: 0.478460  [12864/54000]
loss: 0.351846  [19264/54000]
loss: 0.435898  [25664/54000]
loss: 0.396317  [32064/54000]
loss: 0.679853  [38464/54000]
loss: 0.504546  [44864/54000]
loss: 0.474665  [51264/54000]
epoch 1: train loss 0.4691 | val loss 0.4431 | val acc 0.8318
loss: 0.512989  [   64/54000]
loss: 0.227946  [ 6464/54000]
loss: 0.328278  [12864/54000]
loss: 0.335095  [19264/54000]
loss: 0.350111  [25664/54000]
loss: 0.184126  [32064/54000]
loss: 0.341717  [38464/54000]
loss: 0.433998  [44864/54000]
loss: 0.397668  [51264/54000]
epoch 2: train loss 0.3554 | val loss 0.3521 | val acc 0.8730
loss: 0.255024  [   64/54000]
loss: 0.234995  [ 6464/54000]
loss: 0.222904  [12864/54000]
loss: 0.428493  [19264/54000]
loss: 0.374523  [25664/54000]
loss: 0.469505  [32064/54000]
loss: 0.277538  [38464/54000]
loss: 0.222085  [44864/54000]
loss: 0.265066  [51264/54000]
epoch 3: train loss 0.3177 | val loss 0.3434 | val acc 0.8730
loss: 0.370908  [   64/54000]
loss: 0.353519  [ 6464/54000]
loss: 0.275059  [12864/54000]
loss: 0.315367  [19264/54000]
loss: 0.289937  [25664/54000]
loss: 0.249287  [32064/54000]
loss: 0.215237  [38464/54000]
loss: 0.197544  [44864/54000]
loss: 0.167709  [51264/54000]
epoch 4: train loss 0.2922 | val loss 0.3342 | val acc 0.8752
loss: 0.373951  [   64/54000]
loss: 0.246395  [ 6464/54000]
loss: 0.227409  [12864/54000]
loss: 0.273455  [19264/54000]
loss: 0.248514  [25664/54000]
loss: 0.208271  [32064/54000]
loss: 0.221615  [38464/54000]
loss: 0.195876  [44864/54000]
loss: 0.281612  [51264/54000]
epoch 5: train loss 0.2756 | val loss 0.3578 | val acc 0.8728
loss: 0.386914  [   64/54000]
loss: 0.256893  [ 6464/54000]
loss: 0.220824  [12864/54000]
loss: 0.203134  [19264/54000]
loss: 0.264740  [25664/54000]
loss: 0.361693  [32064/54000]
loss: 0.146999  [38464/54000]
loss: 0.236084  [44864/54000]
loss: 0.203181  [51264/54000]
epoch 6: train loss 0.2587 | val loss 0.3205 | val acc 0.8813
loss: 0.281533  [   64/54000]
loss: 0.162537  [ 6464/54000]
loss: 0.338767  [12864/54000]
loss: 0.221549  [19264/54000]
loss: 0.218362  [25664/54000]
loss: 0.435755  [32064/54000]
loss: 0.188523  [38464/54000]
loss: 0.181538  [44864/54000]
loss: 0.454086  [51264/54000]
epoch 7: train loss 0.2465 | val loss 0.3011 | val acc 0.8888
loss: 0.169964  [   64/54000]
loss: 0.216393  [ 6464/54000]
loss: 0.488910  [12864/54000]
loss: 0.171133  [19264/54000]
loss: 0.252876  [25664/54000]
loss: 0.176113  [32064/54000]
loss: 0.168887  [38464/54000]
loss: 0.101125  [44864/54000]
loss: 0.269060  [51264/54000]
epoch 8: train loss 0.2341 | val loss 0.3485 | val acc 0.8812
loss: 0.192563  [   64/54000]
loss: 0.281194  [ 6464/54000]
loss: 0.242043  [12864/54000]
loss: 0.127259  [19264/54000]
loss: 0.181988  [25664/54000]
loss: 0.253639  [32064/54000]
loss: 0.261181  [38464/54000]
loss: 0.274199  [44864/54000]
loss: 0.246391  [51264/54000]
epoch 9: train loss 0.2202 | val loss 0.3084 | val acc 0.8923
loss: 0.125720  [   64/54000]
loss: 0.210774  [ 6464/54000]
loss: 0.057318  [12864/54000]
loss: 0.323010  [19264/54000]
loss: 0.372432  [25664/54000]
loss: 0.231159  [32064/54000]
loss: 0.225570  [38464/54000]
loss: 0.247707  [44864/54000]
loss: 0.259084  [51264/54000]
Early stopping - epoch 9

=== 3/21: init=xavier ===
training cifar with config {'init': 'xavier', 'activation': 'relu', 'optimizer': 'adam', 'lr': 0.001, 'dropout': 0.0, 'weight_decay': 0.0, 'depth': 2, 'width': 512, 'epochs': 15, 'patience': 3}
loss: 2.395823  [   64/54000]
loss: 0.482352  [ 6464/54000]
loss: 0.454643  [12864/54000]
loss: 0.329675  [19264/54000]
loss: 0.343451  [25664/54000]
loss: 0.426961  [32064/54000]
loss: 0.668837  [38464/54000]
loss: 0.535305  [44864/54000]
loss: 0.475194  [51264/54000]
epoch 1: train loss 0.4744 | val loss 0.4231 | val acc 0.8422
loss: 0.494497  [   64/54000]
loss: 0.240806  [ 6464/54000]
loss: 0.352016  [12864/54000]
loss: 0.335147  [19264/54000]
loss: 0.367952  [25664/54000]
loss: 0.180728  [32064/54000]
loss: 0.286617  [38464/54000]
loss: 0.454392  [44864/54000]
loss: 0.430269  [51264/54000]
epoch 2: train loss 0.3557 | val loss 0.3621 | val acc 0.8675
loss: 0.282682  [   64/54000]
loss: 0.208647  [ 6464/54000]
loss: 0.212618  [12864/54000]
loss: 0.428363  [19264/54000]
loss: 0.349823  [25664/54000]
loss: 0.512855  [32064/54000]
loss: 0.327529  [38464/54000]
loss: 0.185676  [44864/54000]
loss: 0.211232  [51264/54000]
epoch 3: train loss 0.3183 | val loss 0.3379 | val acc 0.8750
loss: 0.376686  [   64/54000]
loss: 0.354019  [ 6464/54000]
loss: 0.246123  [12864/54000]
loss: 0.302456  [19264/54000]
loss: 0.291479  [25664/54000]
loss: 0.234850  [32064/54000]
loss: 0.189131  [38464/54000]
loss: 0.218616  [44864/54000]
loss: 0.157649  [51264/54000]
epoch 4: train loss 0.2948 | val loss 0.3302 | val acc 0.8813
loss: 0.402421  [   64/54000]
loss: 0.235066  [ 6464/54000]
loss: 0.307550  [12864/54000]
loss: 0.236399  [19264/54000]
loss: 0.222694  [25664/54000]
loss: 0.214047  [32064/54000]
loss: 0.226996  [38464/54000]
loss: 0.198141  [44864/54000]
loss: 0.426567  [51264/54000]
epoch 5: train loss 0.2772 | val loss 0.3363 | val acc 0.8787
loss: 0.402238  [   64/54000]
loss: 0.238630  [ 6464/54000]
loss: 0.242664  [12864/54000]
loss: 0.176811  [19264/54000]
loss: 0.299365  [25664/54000]
loss: 0.365239  [32064/54000]
loss: 0.193768  [38464/54000]
loss: 0.209418  [44864/54000]
loss: 0.203279  [51264/54000]
epoch 6: train loss 0.2627 | val loss 0.3271 | val acc 0.8827
loss: 0.287895  [   64/54000]
loss: 0.167994  [ 6464/54000]
loss: 0.343287  [12864/54000]
loss: 0.215954  [19264/54000]
loss: 0.194295  [25664/54000]
loss: 0.375578  [32064/54000]
loss: 0.247796  [38464/54000]
loss: 0.199326  [44864/54000]
loss: 0.540020  [51264/54000]
epoch 7: train loss 0.2493 | val loss 0.3405 | val acc 0.8783
loss: 0.213337  [   64/54000]
loss: 0.241606  [ 6464/54000]
loss: 0.484998  [12864/54000]
loss: 0.177893  [19264/54000]
loss: 0.200600  [25664/54000]
loss: 0.121129  [32064/54000]
loss: 0.188982  [38464/54000]
loss: 0.121856  [44864/54000]
loss: 0.250889  [51264/54000]
epoch 8: train loss 0.2388 | val loss 0.3327 | val acc 0.8807
loss: 0.111041  [   64/54000]
loss: 0.322019  [ 6464/54000]
loss: 0.254630  [12864/54000]
loss: 0.106993  [19264/54000]
loss: 0.213840  [25664/54000]
loss: 0.240194  [32064/54000]
loss: 0.337448  [38464/54000]
loss: 0.329390  [44864/54000]
loss: 0.241855  [51264/54000]
epoch 9: train loss 0.2241 | val loss 0.3004 | val acc 0.8933
loss: 0.167781  [   64/54000]
loss: 0.209146  [ 6464/54000]
loss: 0.073321  [12864/54000]
loss: 0.295822  [19264/54000]
loss: 0.287379  [25664/54000]
loss: 0.308896  [32064/54000]
loss: 0.265053  [38464/54000]
loss: 0.279103  [44864/54000]
loss: 0.225576  [51264/54000]
epoch 10: train loss 0.2158 | val loss 0.3248 | val acc 0.8888
loss: 0.242319  [   64/54000]
loss: 0.182876  [ 6464/54000]
loss: 0.143886  [12864/54000]
loss: 0.312036  [19264/54000]
loss: 0.174488  [25664/54000]
loss: 0.311629  [32064/54000]
loss: 0.349105  [38464/54000]
loss: 0.249203  [44864/54000]
loss: 0.205897  [51264/54000]
epoch 11: train loss 0.2048 | val loss 0.3215 | val acc 0.8887
loss: 0.171760  [   64/54000]
loss: 0.094840  [ 6464/54000]
loss: 0.214684  [12864/54000]
loss: 0.256483  [19264/54000]
loss: 0.196743  [25664/54000]
loss: 0.248688  [32064/54000]
loss: 0.181654  [38464/54000]
loss: 0.237094  [44864/54000]
loss: 0.133225  [51264/54000]
Early stopping - epoch 11

=== 4/21: init=normal ===
training cifar with config {'init': 'normal', 'activation': 'relu', 'optimizer': 'adam', 'lr': 0.001, 'dropout': 0.0, 'weight_decay': 0.0, 'depth': 2, 'width': 512, 'epochs': 15, 'patience': 3}
loss: 2.302745  [   64/54000]
loss: 0.614336  [ 6464/54000]
loss: 0.518648  [12864/54000]
loss: 0.416824  [19264/54000]
loss: 0.333740  [25664/54000]
loss: 0.455498  [32064/54000]
loss: 0.703549  [38464/54000]
loss: 0.514486  [44864/54000]
loss: 0.461889  [51264/54000]
epoch 1: train loss 0.5365 | val loss 0.4229 | val acc 0.8433
loss: 0.491878  [   64/54000]
loss: 0.235506  [ 6464/54000]
loss: 0.337898  [12864/54000]
loss: 0.299028  [19264/54000]
loss: 0.411750  [25664/54000]
loss: 0.195891  [32064/54000]
loss: 0.328611  [38464/54000]
loss: 0.481299  [44864/54000]
loss: 0.498561  [51264/54000]
epoch 2: train loss 0.3710 | val loss 0.3709 | val acc 0.8653
loss: 0.307585  [   64/54000]
loss: 0.267714  [ 6464/54000]
loss: 0.213633  [12864/54000]
loss: 0.441346  [19264/54000]
loss: 0.350924  [25664/54000]
loss: 0.553951  [32064/54000]
loss: 0.300439  [38464/54000]
loss: 0.208870  [44864/54000]
loss: 0.223566  [51264/54000]
epoch 3: train loss 0.3318 | val loss 0.3586 | val acc 0.8730
loss: 0.488563  [   64/54000]
loss: 0.325737  [ 6464/54000]
loss: 0.250656  [12864/54000]
loss: 0.333025  [19264/54000]
loss: 0.302683  [25664/54000]
loss: 0.231708  [32064/54000]
loss: 0.212306  [38464/54000]
loss: 0.212931  [44864/54000]
loss: 0.177745  [51264/54000]
epoch 4: train loss 0.3058 | val loss 0.3361 | val acc 0.8757
loss: 0.397463  [   64/54000]
loss: 0.281377  [ 6464/54000]
loss: 0.203332  [12864/54000]
loss: 0.247670  [19264/54000]
loss: 0.215146  [25664/54000]
loss: 0.226861  [32064/54000]
loss: 0.232979  [38464/54000]
loss: 0.197861  [44864/54000]
loss: 0.337093  [51264/54000]
epoch 5: train loss 0.2860 | val loss 0.3563 | val acc 0.8773
loss: 0.435171  [   64/54000]
loss: 0.285032  [ 6464/54000]
loss: 0.234932  [12864/54000]
loss: 0.187315  [19264/54000]
loss: 0.269226  [25664/54000]
loss: 0.305818  [32064/54000]
loss: 0.171543  [38464/54000]
loss: 0.165321  [44864/54000]
loss: 0.201519  [51264/54000]
epoch 6: train loss 0.2703 | val loss 0.3283 | val acc 0.8795
loss: 0.302062  [   64/54000]
loss: 0.175493  [ 6464/54000]
loss: 0.382459  [12864/54000]
loss: 0.277438  [19264/54000]
loss: 0.279664  [25664/54000]
loss: 0.439955  [32064/54000]
loss: 0.213546  [38464/54000]
loss: 0.178097  [44864/54000]
loss: 0.667417  [51264/54000]
epoch 7: train loss 0.2579 | val loss 0.3122 | val acc 0.8885
loss: 0.166120  [   64/54000]
loss: 0.183861  [ 6464/54000]
loss: 0.469787  [12864/54000]
loss: 0.195946  [19264/54000]
loss: 0.233071  [25664/54000]
loss: 0.126982  [32064/54000]
loss: 0.176275  [38464/54000]
loss: 0.136454  [44864/54000]
loss: 0.280672  [51264/54000]
epoch 8: train loss 0.2436 | val loss 0.3225 | val acc 0.8845
loss: 0.104613  [   64/54000]
loss: 0.262693  [ 6464/54000]
loss: 0.257755  [12864/54000]
loss: 0.146096  [19264/54000]
loss: 0.213064  [25664/54000]
loss: 0.259645  [32064/54000]
loss: 0.263684  [38464/54000]
loss: 0.285683  [44864/54000]
loss: 0.326643  [51264/54000]
epoch 9: train loss 0.2317 | val loss 0.3008 | val acc 0.8933
loss: 0.178493  [   64/54000]
loss: 0.250644  [ 6464/54000]
loss: 0.060372  [12864/54000]
loss: 0.333837  [19264/54000]
loss: 0.366913  [25664/54000]
loss: 0.250018  [32064/54000]
loss: 0.279715  [38464/54000]
loss: 0.261047  [44864/54000]
loss: 0.302502  [51264/54000]
epoch 10: train loss 0.2200 | val loss 0.3176 | val acc 0.8917
loss: 0.253481  [   64/54000]
loss: 0.223907  [ 6464/54000]
loss: 0.172490  [12864/54000]
loss: 0.354561  [19264/54000]
loss: 0.166533  [25664/54000]
loss: 0.256011  [32064/54000]
loss: 0.335239  [38464/54000]
loss: 0.308728  [44864/54000]
loss: 0.235690  [51264/54000]
epoch 11: train loss 0.2126 | val loss 0.3335 | val acc 0.8867
loss: 0.174947  [   64/54000]
loss: 0.096223  [ 6464/54000]
loss: 0.187810  [12864/54000]
loss: 0.349998  [19264/54000]
loss: 0.168329  [25664/54000]
loss: 0.214244  [32064/54000]
loss: 0.170563  [38464/54000]
loss: 0.295516  [44864/54000]
loss: 0.124571  [51264/54000]
Early stopping - epoch 11

=== 5/21: activation=leaky_relu ===
training cifar with config {'init': 'default', 'activation': 'leaky_relu', 'optimizer': 'adam', 'lr': 0.001, 'dropout': 0.0, 'weight_decay': 0.0, 'depth': 2, 'width': 512, 'epochs': 15, 'patience': 3}
loss: 2.304766  [   64/54000]
loss: 0.575328  [ 6464/54000]
loss: 0.709507  [12864/54000]
loss: 0.532193  [19264/54000]
loss: 0.445251  [25664/54000]
loss: 0.357943  [32064/54000]
loss: 0.282232  [38464/54000]
loss: 0.283849  [44864/54000]
loss: 0.416540  [51264/54000]
epoch 1: train loss 0.4948 | val loss 0.3987 | val acc 0.8550
loss: 0.364914  [   64/54000]
loss: 0.494521  [ 6464/54000]
loss: 0.287879  [12864/54000]
loss: 0.384967  [19264/54000]
loss: 0.522589  [25664/54000]
loss: 0.322207  [32064/54000]
loss: 0.379026  [38464/54000]
loss: 0.440536  [44864/54000]
loss: 0.434645  [51264/54000]
epoch 2: train loss 0.3633 | val loss 0.3522 | val acc 0.8710
loss: 0.466653  [   64/54000]
loss: 0.289134  [ 6464/54000]
loss: 0.330782  [12864/54000]
loss: 0.258173  [19264/54000]
loss: 0.434225  [25664/54000]
loss: 0.353091  [32064/54000]
loss: 0.192643  [38464/54000]
loss: 0.382425  [44864/54000]
loss: 0.319133  [51264/54000]
epoch 3: train loss 0.3231 | val loss 0.3794 | val acc 0.8663
loss: 0.401865  [   64/54000]
loss: 0.295135  [ 6464/54000]
loss: 0.213174  [12864/54000]
loss: 0.460855  [19264/54000]
loss: 0.304629  [25664/54000]
loss: 0.316168  [32064/54000]
loss: 0.248547  [38464/54000]
loss: 0.340423  [44864/54000]
loss: 0.263588  [51264/54000]
epoch 4: train loss 0.3027 | val loss 0.3357 | val acc 0.8765
loss: 0.251296  [   64/54000]
loss: 0.275196  [ 6464/54000]
loss: 0.422898  [12864/54000]
loss: 0.453484  [19264/54000]
loss: 0.290285  [25664/54000]
loss: 0.202283  [32064/54000]
loss: 0.200553  [38464/54000]
loss: 0.328661  [44864/54000]
loss: 0.358436  [51264/54000]
epoch 5: train loss 0.2799 | val loss 0.3125 | val acc 0.8860
loss: 0.251253  [   64/54000]
loss: 0.185037  [ 6464/54000]
loss: 0.269676  [12864/54000]
loss: 0.390633  [19264/54000]
loss: 0.208344  [25664/54000]
loss: 0.319014  [32064/54000]
loss: 0.335371  [38464/54000]
loss: 0.403634  [44864/54000]
loss: 0.207766  [51264/54000]
epoch 6: train loss 0.2644 | val loss 0.3525 | val acc 0.8703
loss: 0.195382  [   64/54000]
loss: 0.161182  [ 6464/54000]
loss: 0.385599  [12864/54000]
loss: 0.277053  [19264/54000]
loss: 0.384327  [25664/54000]
loss: 0.179803  [32064/54000]
loss: 0.213202  [38464/54000]
loss: 0.316579  [44864/54000]
loss: 0.143785  [51264/54000]
epoch 7: train loss 0.2516 | val loss 0.3187 | val acc 0.8833
loss: 0.172411  [   64/54000]
loss: 0.152016  [ 6464/54000]
loss: 0.186352  [12864/54000]
loss: 0.152510  [19264/54000]
loss: 0.343587  [25664/54000]
loss: 0.241595  [32064/54000]
loss: 0.284805  [38464/54000]
loss: 0.255009  [44864/54000]
loss: 0.321334  [51264/54000]
Early stopping - epoch 7

=== 6/21: activation=gelu ===
training cifar with config {'init': 'default', 'activation': 'gelu', 'optimizer': 'adam', 'lr': 0.001, 'dropout': 0.0, 'weight_decay': 0.0, 'depth': 2, 'width': 512, 'epochs': 15, 'patience': 3}
loss: 2.303245  [   64/54000]
loss: 0.547646  [ 6464/54000]
loss: 0.655641  [12864/54000]
loss: 0.533250  [19264/54000]
loss: 0.371491  [25664/54000]
loss: 0.315847  [32064/54000]
loss: 0.319383  [38464/54000]
loss: 0.283824  [44864/54000]
loss: 0.358345  [51264/54000]
epoch 1: train loss 0.4864 | val loss 0.4132 | val acc 0.8500
loss: 0.378012  [   64/54000]
loss: 0.508862  [ 6464/54000]
loss: 0.330185  [12864/54000]
loss: 0.349284  [19264/54000]
loss: 0.488530  [25664/54000]
loss: 0.276798  [32064/54000]
loss: 0.355335  [38464/54000]
loss: 0.386848  [44864/54000]
loss: 0.407045  [51264/54000]
epoch 2: train loss 0.3516 | val loss 0.3471 | val acc 0.8735
loss: 0.455292  [   64/54000]
loss: 0.248401  [ 6464/54000]
loss: 0.302482  [12864/54000]
loss: 0.248661  [19264/54000]
loss: 0.396989  [25664/54000]
loss: 0.313006  [32064/54000]
loss: 0.182970  [38464/54000]
loss: 0.325001  [44864/54000]
loss: 0.304528  [51264/54000]
epoch 3: train loss 0.3092 | val loss 0.3505 | val acc 0.8740
loss: 0.315123  [   64/54000]
loss: 0.302997  [ 6464/54000]
loss: 0.215321  [12864/54000]
loss: 0.396868  [19264/54000]
loss: 0.235784  [25664/54000]
loss: 0.335470  [32064/54000]
loss: 0.213283  [38464/54000]
loss: 0.317179  [44864/54000]
loss: 0.223004  [51264/54000]
epoch 4: train loss 0.2829 | val loss 0.3294 | val acc 0.8743
loss: 0.233663  [   64/54000]
loss: 0.254401  [ 6464/54000]
loss: 0.418692  [12864/54000]
loss: 0.348362  [19264/54000]
loss: 0.243648  [25664/54000]
loss: 0.261613  [32064/54000]
loss: 0.173931  [38464/54000]
loss: 0.348835  [44864/54000]

,name,init,activation,optimizer,lr,dropout,weight_decay,depth,width,epochs,patience,config,best_val_loss,best_val_acc,best_epoch,params
8,"optimizer=sgd, lr=0.01",default,relu,sgd,0.0100,0.0,0.0000,2,512,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.289119,0.894333,15,669706
5,activation=gelu,default,gelu,adam,0.0010,0.0,0.0000,2,512,15,3,"{'init': 'default', 'activation': 'gelu', 'opt...",0.294943,0.892833,7,669706
2,init=xavier,xavier,relu,adam,0.0010,0.0,0.0000,2,512,15,3,"{'init': 'xavier', 'activation': 'relu', 'opti...",0.300400,0.893333,9,669706
3,init=normal,normal,relu,adam,0.0010,0.0,0.0000,2,512,15,3,"{'init': 'normal', 'activation': 'relu', 'opti...",0.300835,0.893333,9,669706
1,init=kaiming,kaiming,relu,adam,0.0010,0.0,0.0000,2,512,15,3,"{'init': 'kaiming', 'activation': 'relu', 'opt...",0.301111,0.888833,7,669706
16,"dropout=0.2, optimizer=adamw, weight_decay=0.01",default,relu,adamw,0.0010,0.2,0.0100,2,512,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.301773,0.889500,12,669706
9,"optimizer=adam, lr=0.0001",default,relu,adam,0.0001,0.0,0.0000,2,512,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.303275,0.886833,15,669706
11,"optimizer=adamw, lr=0.0001",default,relu,adamw,0.0001,0.0,0.0000,2,512,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.303275,0.886833,15,669706
17,depth=1,default,relu,adam,0.0010,0.0,0.0000,1,512,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.306376,0.887500,8,407050
12,dropout=0.2,default,relu,adam,0.0010,0.2,0.0000,2,512,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.309021,0.882667,7,669706
15,"optimizer=adamw, weight_decay=0.01",default,relu,adamw,0.0010,0.0,0.0100,2,512,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.309331,0.887500,7,669706
0,baseline,default,relu,adam,0.0010,0.0,0.0000,2,512,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.310788,0.884167,7,669706
10,"optimizer=adamw, lr=0.001",default,relu,adamw,0.0010,0.0,0.0000,2,512,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.310788,0.884167,7,669706
4,activation=leaky_relu,default,leaky_relu,adam,0.0010,0.0,0.0000,2,512,15,3,"{'init': 'default', 'activation': 'leaky_relu'...",0.312459,0.886000,5,669706
19,width=128,default,relu,adam,0.0010,0.0,0.0000,2,128,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.312570,0.888833,14,118282
20,width=1024,default,relu,adam,0.0010,0.0,0.0000,2,1024,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.314956,0.886333,5,1863690
18,depth=4,default,relu,adam,0.0010,0.0,0.0000,4,512,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.315980,0.885333,8,1195018
14,weight_decay=0.0001,default,relu,adam,0.0010,0.0,0.0001,2,512,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.316046,0.884500,7,669706
6,activation=tanh,default,tanh,adam,0.0010,0.0,0.0000,2,512,15,3,"{'init': 'default', 'activation': 'tanh', 'opt...",0.321041,0.889000,10,669706
13,dropout=0.5,default,relu,adam,0.0010,0.5,0.0000,2,512,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.322382,0.881500,14,669706
7,"optimizer=sgd, lr=0.1",default,relu,sgd,0.1000,0.0,0.0000,2,512,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",0.369688,0.877000,10,669706

In [35]:
##Compare datasets
transform = v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])

# Download training data from open datasets.
training_cifar = datasets.CIFAR10(
    root="data",
    train=True,
    download=True,
    transform=transform,
)

# Download test data from open datasets.
test_cifar = datasets.CIFAR10(
    root="data",
    train=False,
    download=True,
    transform=transform,
)

# Split 10% of the training data for validation
generator = torch.Generator().manual_seed(42)
train_cifar, val_cifar = random_split(training_cifar, [45000, 5000], generator=generator)

Files already downloaded and verified
Files already downloaded and verified

In [36]:
df_copy = df.copy()
top3_cfgs =  df_copy.head(3)["config"].tolist()

batch_size = 64
# Create data loaders.
train_cifar_dataloader = DataLoader(train_cifar, batch_size=batch_size, shuffle=True)
test_cifar_dataloader = DataLoader(test_cifar, batch_size=batch_size)
val_cifar_dataloader = DataLoader(val_cifar, batch_size=batch_size)

print("best 3")
print(top3_cfgs)

results_cifar = []
count=0

for confg in top3_cfgs:

    train_for_configuration_and_datasets(cfg=confg,
                                             train_dataloader=train_cifar_dataloader,
                                             val_dataloader=val_cifar_dataloader,
                                             results=results_cifar,
                                             in_features= 32 * 32 * 3,
                                             name=f'Cfiar_run{count}')

    count+=1

df_cifar = pd.DataFrame(results_cifar).drop(columns="history").sort_values("best_val_loss")
df_cifar

best 3
[{'init': 'default', 'activation': 'relu', 'optimizer': 'sgd', 'lr': 0.01, 'dropout': 0.0, 'weight_decay': 0.0, 'depth': 2, 'width': 512, 'epochs': 15, 'patience': 3}, {'init': 'default', 'activation': 'gelu', 'optimizer': 'adam', 'lr': 0.001, 'dropout': 0.0, 'weight_decay': 0.0, 'depth': 2, 'width': 512, 'epochs': 15, 'patience': 3}, {'init': 'xavier', 'activation': 'relu', 'optimizer': 'adam', 'lr': 0.001, 'dropout': 0.0, 'weight_decay': 0.0, 'depth': 2, 'width': 512, 'epochs': 15, 'patience': 3}]
training with config {'init': 'default', 'activation': 'relu', 'optimizer': 'sgd', 'lr': 0.01, 'dropout': 0.0, 'weight_decay': 0.0, 'depth': 2, 'width': 512, 'epochs': 15, 'patience': 3}
loss: 2.299861  [   64/45000]
loss: 2.005317  [ 6464/45000]
loss: 1.903166  [12864/45000]
loss: 1.814225  [19264/45000]
loss: 1.789012  [25664/45000]
loss: 1.824506  [32064/45000]
loss: 1.814707  [38464/45000]
loss: 1.675971  [44864/45000]
epoch 1: train loss 1.8840 | val loss 1.7168 | val acc 0.3862
loss: 1.625982  [   64/45000]
loss: 1.843740  [ 6464/45000]
loss: 1.609725  [12864/45000]
loss: 1.867146  [19264/45000]
loss: 1.653126  [25664/45000]
loss: 1.644770  [32064/45000]
loss: 1.719665  [38464/45000]
loss: 1.442736  [44864/45000]
epoch 2: train loss 1.6796 | val loss 1.6513 | val acc 0.4082
loss: 1.697286  [   64/45000]
loss: 1.744328  [ 6464/45000]
loss: 1.543166  [12864/45000]
loss: 1.597657  [19264/45000]
loss: 1.403728  [25664/45000]
loss: 2.030176  [32064/45000]
loss: 1.440514  [38464/45000]
loss: 1.617616  [44864/45000]
epoch 3: train loss 1.5901 | val loss 1.6013 | val acc 0.4284
loss: 1.578774  [   64/45000]
loss: 1.478043  [ 6464/45000]
loss: 1.552160  [12864/45000]
loss: 1.523201  [19264/45000]
loss: 1.568331  [25664/45000]
loss: 1.580848  [32064/45000]
loss: 1.507873  [38464/45000]
loss: 1.403644  [44864/45000]
epoch 4: train loss 1.5381 | val loss 1.6561 | val acc 0.4134
loss: 1.572442  [   64/45000]
loss: 1.538849  [ 6464/45000]
loss: 1.322231  [12864/45000]
loss: 1.386753  [19264/45000]
loss: 1.739855  [25664/45000]
loss: 1.541253  [32064/45000]
loss: 1.606873  [38464/45000]
loss: 1.515055  [44864/45000]
epoch 5: train loss 1.4957 | val loss 1.5198 | val acc 0.4554
loss: 1.353297  [   64/45000]
loss: 1.489345  [ 6464/45000]
loss: 1.508595  [12864/45000]
loss: 1.277054  [19264/45000]
loss: 1.593675  [25664/45000]
loss: 1.356165  [32064/45000]
loss: 1.482931  [38464/45000]
loss: 1.230364  [44864/45000]
epoch 6: train loss 1.4487 | val loss 1.5278 | val acc 0.4556
loss: 1.494587  [   64/45000]
loss: 1.442088  [ 6464/45000]
loss: 1.283938  [12864/45000]
loss: 1.375876  [19264/45000]
loss: 1.316877  [25664/45000]
loss: 1.320962  [32064/45000]
loss: 1.381970  [38464/45000]
loss: 1.233038  [44864/45000]
epoch 7: train loss 1.4150 | val loss 1.4532 | val acc 0.4866
loss: 1.513530  [   64/45000]
loss: 1.825174  [ 6464/45000]
loss: 1.341898  [12864/45000]
loss: 1.479478  [19264/45000]
loss: 1.513810  [25664/45000]
loss: 1.199425  [32064/45000]
loss: 1.729301  [38464/45000]
loss: 1.522095  [44864/45000]
epoch 8: train loss 1.3734 | val loss 1.4310 | val acc 0.4932
loss: 1.297847  [   64/45000]
loss: 1.202363  [ 6464/45000]
loss: 1.529877  [12864/45000]
loss: 1.184702  [19264/45000]
loss: 1.401722  [25664/45000]
loss: 1.193284  [32064/45000]
loss: 1.254373  [38464/45000]
loss: 1.451135  [44864/45000]
epoch 9: train loss 1.3438 | val loss 1.4122 | val acc 0.4974
loss: 1.354993  [   64/45000]
loss: 1.264442  [ 6464/45000]
loss: 1.212581  [12864/45000]
loss: 1.285840  [19264/45000]
loss: 1.249499  [25664/45000]
loss: 1.326880  [32064/45000]
loss: 1.187559  [38464/45000]
loss: 1.596724  [44864/45000]
epoch 10: train loss 1.3114 | val loss 1.4003 | val acc 0.5006
loss: 1.498614  [   64/45000]
loss: 1.323011  [ 6464/45000]
loss: 1.168169  [12864/45000]
loss: 1.164889  [19264/45000]
loss: 1.383085  [25664/45000]
loss: 1.347369  [32064/45000]
loss: 1.120910  [38464/45000]
loss: 1.289778  [44864/45000]
epoch 11: train loss 1.2774 | val loss 1.4136 | val acc 0.5050
loss: 1.352934  [   64/45000]
loss: 1.160889  [ 6464/45000]
loss: 1.082662  [12864/45000]
loss: 1.524932  [19264/45000]
loss: 1.069871  [25664/45000]
loss: 1.336040  [32064/45000]
loss: 1.221078  [38464/45000]
loss: 1.408967  [44864/45000]
epoch 12: train loss 1.2500 | val loss 1.4199 | val acc 0.5060
loss: 1.164975  [   64/45000]
loss: 1.123532  [ 6464/45000]
loss: 0.977681  [12864/45000]
loss: 1.424965  [19264/45000]
loss: 1.266571  [25664/45000]
loss: 1.244483  [32064/45000]
loss: 1.200040  [38464/45000]
loss: 1.033236  [44864/45000]
epoch 13: train loss 1.2238 | val loss 1.3684 | val acc 0.5204
loss: 1.187087  [   64/45000]
loss: 1.048253  [ 6464/45000]
loss: 1.421695  [12864/45000]
loss: 1.092855  [19264/45000]
loss: 1.125079  [25664/45000]
loss: 1.294055  [32064/45000]
loss: 1.126900  [38464/45000]
loss: 0.959729  [44864/45000]
epoch 14: train loss 1.1930 | val loss 1.3707 | val acc 0.5202
loss: 1.251239  [   64/45000]
loss: 1.127022  [ 6464/45000]
loss: 1.216563  [12864/45000]
loss: 1.195033  [19264/45000]
loss: 1.133918  [25664/45000]
loss: 1.074690  [32064/45000]
loss: 1.319882  [38464/45000]
loss: 1.370709  [44864/45000]
epoch 15: train loss 1.1685 | val loss 1.3853 | val acc 0.5202
training with config {'init': 'default', 'activation': 'gelu', 'optimizer': 'adam', 'lr': 0.001, 'dropout': 0.0, 'weight_decay': 0.0, 'depth': 2, 'width': 512, 'epochs': 15, 'patience': 3}
loss: 2.302040  [   64/45000]
loss: 1.916024  [ 6464/45000]
loss: 1.895819  [12864/45000]
loss: 1.823896  [19264/45000]
loss: 1.643470  [25664/45000]
loss: 1.845337  [32064/45000]
loss: 1.746179  [38464/45000]
loss: 1.657495  [44864/45000]
epoch 1: train loss 1.8392 | val loss 1.6796 | val acc 0.3942
loss: 1.653676  [   64/45000]
loss: 1.763364  [ 6464/45000]
loss: 1.483655  [12864/45000]
loss: 1.703896  [19264/45000]
loss: 1.607988  [25664/45000]
loss: 1.742220  [32064/45000]
loss: 1.732441  [38464/45000]
loss: 1.443440  [44864/45000]
epoch 2: train loss 1.6495 | val loss 1.6175 | val acc 0.4246
loss: 1.589124  [   64/45000]
loss: 1.712084  [ 6464/45000]
loss: 1.520277  [12864/45000]
loss: 1.525835  [19264/45000]
loss: 1.364443  [25664/45000]
loss: 1.858519  [32064/45000]
loss: 1.418521  [38464/45000]
loss: 1.613506  [44864/45000]
epoch 3: train loss 1.5562 | val loss 1.5786 | val acc 0.4378
loss: 1.464266  [   64/45000]
loss: 1.513267  [ 6464/45000]
loss: 1.537277  [12864/45000]
loss: 1.477787  [19264/45000]
loss: 1.642463  [25664/45000]
loss: 1.448699  [32064/45000]
loss: 1.373221  [38464/45000]
loss: 1.479360  [44864/45000]
epoch 4: train loss 1.4991 | val loss 1.5702 | val acc 0.4394
loss: 1.434606  [   64/45000]
loss: 1.592783  [ 6464/45000]
loss: 1.353619  [12864/45000]
loss: 1.358147  [19264/45000]
loss: 1.769825  [25664/45000]
loss: 1.505529  [32064/45000]
loss: 1.516888  [38464/45000]
loss: 1.437412  [44864/45000]
epoch 5: train loss 1.4583 | val loss 1.5080 | val acc 0.4652
loss: 1.332855  [   64/45000]
loss: 1.494076  [ 6464/45000]
loss: 1.476147  [12864/45000]
loss: 1.272575  [19264/45000]
loss: 1.509348  [25664/45000]
loss: 1.339863  [32064/45000]
loss: 1.356676  [38464/45000]
loss: 1.168723  [44864/45000]
epoch 6: train loss 1.4146 | val loss 1.4989 | val acc 0.4614
loss: 1.477356  [   64/45000]
loss: 1.368369  [ 6464/45000]
loss: 1.269547  [12864/45000]
loss: 1.316635  [19264/45000]
loss: 1.205223  [25664/45000]
loss: 1.327598  [32064/45000]
loss: 1.377501  [38464/45000]
loss: 1.217904  [44864/45000]
epoch 7: train loss 1.3897 | val loss 1.4588 | val acc 0.4810
loss: 1.464563  [   64/45000]
loss: 1.802919  [ 6464/45000]
loss: 1.292324  [12864/45000]
loss: 1.482533  [19264/45000]
loss: 1.400881  [25664/45000]
loss: 1.267231  [32064/45000]
loss: 1.629550  [38464/45000]
loss: 1.456538  [44864/45000]
epoch 8: train loss 1.3513 | val loss 1.4453 | val acc 0.4914
loss: 1.210251  [   64/45000]
loss: 1.101418  [ 6464/45000]
loss: 1.500013  [12864/45000]
loss: 1.105858  [19264/45000]
loss: 1.304772  [25664/45000]
loss: 1.203807  [32064/45000]
loss: 1.276881  [38464/45000]
loss: 1.520081  [44864/45000]
epoch 9: train loss 1.3250 | val loss 1.4352 | val acc 0.4966
loss: 1.270762  [   64/45000]
loss: 1.254190  [ 6464/45000]
loss: 1.247762  [12864/45000]
loss: 1.365197  [19264/45000]
loss: 1.226703  [25664/45000]
loss: 1.226568  [32064/45000]
loss: 1.150535  [38464/45000]
loss: 1.515270  [44864/45000]
epoch 10: train loss 1.2969 | val loss 1.4246 | val acc 0.4918
loss: 1.493528  [   64/45000]
loss: 1.334360  [ 6464/45000]
loss: 1.227114  [12864/45000]
loss: 1.262242  [19264/45000]
loss: 1.363240  [25664/45000]
loss: 1.323938  [32064/45000]
loss: 1.133442  [38464/45000]
loss: 1.166234  [44864/45000]
epoch 11: train loss 1.2715 | val loss 1.5230 | val acc 0.4622
loss: 1.386154  [   64/45000]
loss: 1.129358  [ 6464/45000]
loss: 1.208606  [12864/45000]
loss: 1.447078  [19264/45000]
loss: 1.161702  [25664/45000]
loss: 1.318661  [32064/45000]
loss: 1.119585  [38464/45000]
loss: 1.270527  [44864/45000]
epoch 12: train loss 1.2422 | val loss 1.4608 | val acc 0.4828
loss: 1.104062  [   64/45000]
loss: 1.182437  [ 6464/45000]
loss: 0.930584  [12864/45000]
loss: 1.367272  [19264/45000]
loss: 1.298749  [25664/45000]
loss: 1.210967  [32064/45000]
loss: 1.231384  [38464/45000]
loss: 1.060611  [44864/45000]
Early stopping - epoch 12
training with config {'init': 'xavier', 'activation': 'relu', 'optimizer': 'adam', 'lr': 0.001, 'dropout': 0.0, 'weight_decay': 0.0, 'depth': 2, 'width': 512, 'epochs': 15, 'patience': 3}
loss: 2.324897  [   64/45000]
loss: 1.971906  [ 6464/45000]
loss: 2.093261  [12864/45000]
loss: 1.723873  [19264/45000]
loss: 1.817036  [25664/45000]
loss: 1.834179  [32064/45000]
loss: 1.681148  [38464/45000]
loss: 1.667515  [44864/45000]
epoch 1: train loss 1.8649 | val loss 1.7035 | val acc 0.3846
loss: 1.579404  [   64/45000]
loss: 1.793133  [ 6464/45000]
loss: 1.627751  [12864/45000]
loss: 1.834472  [19264/45000]
loss: 1.571933  [25664/45000]
loss: 1.530799  [32064/45000]
loss: 1.815839  [38464/45000]
loss: 1.852383  [44864/45000]
epoch 2: train loss 1.6721 | val loss 1.6912 | val acc 0.3818
loss: 1.697390  [   64/45000]
loss: 1.514922  [ 6464/45000]
loss: 1.524329  [12864/45000]
loss: 1.770368  [19264/45000]
loss: 1.505278  [25664/45000]
loss: 1.552718  [32064/45000]
loss: 1.495157  [38464/45000]
loss: 1.360671  [44864/45000]
epoch 3: train loss 1.5853 | val loss 1.6092 | val acc 0.4342
loss: 1.638667  [   64/45000]
loss: 1.496600  [ 6464/45000]
loss: 1.655376  [12864/45000]
loss: 1.706974  [19264/45000]
loss: 1.585193  [25664/45000]
loss: 1.514248  [32064/45000]
loss: 1.532105  [38464/45000]
loss: 1.653391  [44864/45000]
epoch 4: train loss 1.5405 | val loss 1.5456 | val acc 0.4518
loss: 1.698999  [   64/45000]
loss: 1.466353  [ 6464/45000]
loss: 1.624479  [12864/45000]
loss: 1.481767  [19264/45000]
loss: 1.439374  [25664/45000]
loss: 1.415959  [32064/45000]
loss: 1.482542  [38464/45000]
loss: 1.389892  [44864/45000]
epoch 5: train loss 1.4944 | val loss 1.5477 | val acc 0.4496
loss: 1.409500  [   64/45000]
loss: 1.453799  [ 6464/45000]
loss: 1.452686  [12864/45000]
loss: 1.733115  [19264/45000]
loss: 1.432223  [25664/45000]
loss: 1.694575  [32064/45000]
loss: 1.354119  [38464/45000]
loss: 1.590807  [44864/45000]
epoch 6: train loss 1.4641 | val loss 1.5174 | val acc 0.4612
loss: 1.533879  [   64/45000]
loss: 1.481582  [ 6464/45000]
loss: 1.635698  [12864/45000]
loss: 1.314664  [19264/45000]
loss: 1.390895  [25664/45000]
loss: 1.236433  [32064/45000]
loss: 1.406591  [38464/45000]
loss: 1.568104  [44864/45000]
epoch 7: train loss 1.4296 | val loss 1.4797 | val acc 0.4718
loss: 1.458604  [   64/45000]
loss: 1.330544  [ 6464/45000]
loss: 1.457987  [12864/45000]
loss: 1.499707  [19264/45000]
loss: 1.362846  [25664/45000]
loss: 1.233969  [32064/45000]
loss: 1.354378  [38464/45000]
loss: 1.371492  [44864/45000]
epoch 8: train loss 1.4083 | val loss 1.4889 | val acc 0.4646
loss: 1.553446  [   64/45000]
loss: 1.140164  [ 6464/45000]
loss: 1.428035  [12864/45000]
loss: 1.154742  [19264/45000]
loss: 1.562462  [25664/45000]
loss: 1.418573  [32064/45000]
loss: 1.522508  [38464/45000]
loss: 1.386374  [44864/45000]
epoch 9: train loss 1.3910 | val loss 1.5080 | val acc 0.4578
loss: 1.368644  [   64/45000]
loss: 1.317704  [ 6464/45000]
loss: 1.447356  [12864/45000]
loss: 1.134665  [19264/45000]
loss: 1.603246  [25664/45000]
loss: 1.272737  [32064/45000]
loss: 1.209477  [38464/45000]
loss: 1.350969  [44864/45000]
Early stopping - epoch 9

,name,init,activation,optimizer,lr,dropout,weight_decay,depth,width,epochs,patience,config,best_val_loss,best_val_acc,best_epoch,params
0,Cfiar_run0,default,relu,sgd,0.010,0.0,0.0,2,512,15,3,"{'init': 'default', 'activation': 'relu', 'opt...",1.368423,0.5204,13,1841162
1,Cfiar_run1,default,gelu,adam,0.001,0.0,0.0,2,512,15,3,"{'init': 'default', 'activation': 'gelu', 'opt...",1.424590,0.4918,10,1841162
2,Cfiar_run2,xavier,relu,adam,0.001,0.0,0.0,2,512,15,3,"{'init': 'xavier', 'activation': 'relu', 'opti...",1.479687,0.4718,7,1841162

In [ ]:
#### Making the plots for the baseline MLP
import matplotlib.pyplot as plt

def plot_history(history, title="Baseline"):
    epochs = range(1, len(history["train_loss"]) + 1)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4))

    ax1.plot(epochs, history["train_loss"], label="train")
    ax1.plot(epochs, history["val_loss"], label="validation")
    ax1.set_xlabel("epoch")
    ax1.set_ylabel("cross-entropy loss")
    ax1.set_title("Loss")
    ax1.legend()

    ax2.plot(epochs, history["val_acc"], label="validation", color="tab:orange")
    ax2.set_xlabel("epoch")
    ax2.set_ylabel("accuracy")
    ax2.set_title("Validation accuracy")
    ax2.legend()

    fig.suptitle(title)
    fig.tight_layout()
    #plt.show()
    plt.savefig(f"{title}.png", dpi=150, bbox_inches="tight")
    plt.close()


def plot_comparison(results, metric="val_loss", title=None):
    """One curve per experiment, for a single metric."""
    plt.figure(figsize=(7, 4))
    for name, history in results.items():
        epochs = range(1, len(history[metric]) + 1)
        plt.plot(epochs, history[metric], label=name)
    plt.xlabel("epoch")
    plt.ylabel(metric)
    plt.title(title or metric)
    plt.legend()
    plt.tight_layout()
    plt.savefig(f"{title}.png", dpi=150, bbox_inches="tight")
    plt.close()

In [ ]:
plot_history(history)
# later, once you have several runs:

In [ ]:
### Making the baseline Convolutional Neural Network (CNN)
class CNN(nn.Module):
    def __init__(self, in_channels=1, image_size=28, activation=nn.ReLU, dropout=0.0):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)

        # Fully connected layers
        size = ((image_size - 4) // 2 - 4) // 2
        self.fc1 = nn.Linear(16 * size * size, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

        self.act = activation()
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        x = self.pool(self.act(self.conv1(x)))
        x = self.pool(self.act(self.conv2(x)))
        x = torch.flatten(x, 1)
        x = self.dropout(self.act(self.fc1(x)))
        x = self.dropout(self.act(self.fc2(x)))
        x = self.fc3(x)
        return x

In [ ]:
torch.manual_seed(42)
model = CNN().to(device)
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

history_cnn = {"train_loss": [], "val_loss": [], "val_acc": []}
for epoch in range(epochs):
    train_loss = train_epoch(model, train_dataloader, loss_fn, optimizer)
    val_loss, val_acc = evaluate(model, val_dataloader, loss_fn)
    history_cnn["train_loss"].append(train_loss)
    history_cnn["val_loss"].append(val_loss)
    history_cnn["val_acc"].append(val_acc)
    print(f"epoch {epoch+1}: train loss {train_loss:.4f} | val loss {val_loss:.4f} | val acc {val_acc:.4f}")

plot_history(history_cnn)

In [ ]:
plot_history(history, title="Baseline MLP")
plot_history(history_cnn, title="Baseline CNN")
# MLP vs CNN baseline
baselines = {"MLP": history, "CNN": history_cnn}
plot_comparison(baselines, metric="val_loss", title="Baselines: validation loss")
plot_comparison(baselines, metric="val_acc", title="Baselines: validation accuracy")